/usr/local/python36/lib/python3.6/site-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2018-11-13 16:18:42,277: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
[2018-11-13 16:18:42,284: INFO/MainProcess] mingle: searching for neighbors
[2018-11-13 16:18:43,346: INFO/MainProcess] mingle: all alone
[2018-11-13 16:18:43,352: INFO/MainProcess] celery@ubuntu ready.
